name = "x402-clarity"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[vars]
NETWORK = "mainnet"
RECIPIENT_ADDRESS = "bc1qv8dt3v9kx3l7r9mnz2gj9r9n9k63frn6w6zmrt"
RESULTS_BASE_URL = "https://cocoa007.github.io/clarity-audit"

[[kv_namespaces]]
binding = "AUDIT_KV"
id = "2d554dd968e3480e912f73f8642704cb"
preview_id = "0939ff1f58e74915a9e510228d840f5e"
